FROM golang:1.23.2-alpine

# Install system dependencies
RUN apk add --no-cache make git curl bash nodejs npm

# Install Tailwind CSS standalone binary
RUN curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -o /usr/local/bin/tailwindcss && \
    chmod +x /usr/local/bin/tailwindcss

# Install Go tools
RUN go install github.com/a-h/templ/cmd/templ@latest && \
    go install github.com/air-verse/air@v1.52.3

WORKDIR /build

# Set PATH to include Go binaries
ENV PATH="/go/bin:${PATH}"

CMD ["air"]
